name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: andres64372/backend-aeroptimal:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Apply changes to server
        run: |
          docker compose pull backend-aeroptimal
          docker compose up --no-deps -d backend-aeroptimal
          docker image prune -f